apiVersion: v1
kind: ConfigMap
metadata:
  name: takserver-config
  namespace: takserver
data:
  # Add your CoreConfig.xml here
  CoreConfig.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration xmlns="http://bbn.com/marti/xml/config"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="CoreConfig.xsd">
        <network multicastTTL="5">
            <input _name="stdssl" protocol="tls" port="8089" coreVersion="2"/>
            <connector port="8443" _name="https"/>
            <connector port="8444" useFederationTruststore="true" _name="fed_https"/>
            <connector port="8446" clientAuth="false" _name="cert_https"/>
        </network>
        <auth>
            <!-- Configure authentication as needed -->
        </auth>
        <!-- Add other configurations -->
        <submission ignoreStaleMessages="false" validateXml="false"/>

        <subscription reloadPersistent="false">
            <!-- example static subscription that publishes messages to a UDP multicast address and port -->
            <!-- <static _name="MulticastProxy" protocol="udp" address="239.2.3.1" port="6969" /> -->
        </subscription>

        <repository enable="true" numDbConnections="16" primaryKeyBatchSize="500" insertionBatchSize="500">
          <connection url="jdbc:postgresql://tak-database:5432/cot" username="martiuser" password="" />
        </repository>

        <repeater enable="true" periodMillis="3000" staleDelayMillis="15000">
            <!-- Examples -->
            <repeatableType initiate-test="/event/detail/emergency[@type='911 Alert']" cancel-test="/event/detail/emergency[@cancel='true']" _name="911"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Ring The Bell']" cancel-test="/event/detail/emergency[@cancel='true']" _name="RingTheBell"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Geo-fence Breached']" cancel-test="/event/detail/emergency[@cancel='true']" _name="GeoFenceBreach"/>
            <repeatableType initiate-test="/event/detail/emergency[@type='Troops In Contact']" cancel-test="/event/detail/emergency[@cancel='true']" _name="TroopsInContact"/>
        </repeater>

        <dissemination smartRetry="false" />

        <filter>
            <flowtag enable="false" text=""/>
            <streamingbroker enable="true"/>
            <!--
            <dropfilter>
                <typefilter type="u-d-p" />
                <typefilter type="u-d-c" />
            </dropfilter>
            -->
            <scrubber enable="false" action="overwrite"/>
        </filter>

        <buffer>
            <latestSA enable="true"/>
            <queue/>
        </buffer>
    </Configuration>