apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver-db
  namespace: takserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver-db
  template:
    metadata:
      labels:
        app: takserver-db
    spec:
      containers:
      - name: tak-server-db
        image: registry.workload.example.com/tak-server-db:v1-amd64 # Build your image 
        env:
        - name: POSTGRES_DB
          value: tak
        - name: POSTGRES_USER
          value: tak
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: takserver-secrets
              key: db-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
        - name: tak-scripts
          mountPath: /opt/tak
          readOnly: true
        command: ["/opt/tak/db-utils/configureInDocker.sh"]
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: takserver-db-pvc
      - name: tak-scripts
        configMap:
          name: takserver-config  # Note: This should be adjusted to include scripts