apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: takserver-gateway
  namespace: takserver
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
spec:
  gatewayClassName: kommander-traefik 
  listeners:
  - name: https
    hostname: takserver.example.com
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: takserver-tls  # Reference to a Secret containing the TLS cert
        kind: Secret
    