apiVersion: v1
kind: Service
metadata:
  name: takserver
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: takserver
  ports:
  - name: tls
    port: 8089
    targetPort: 8089
  - name: https
    port: 8443
    targetPort: 8443
  - name: fed-https
    port: 8444
    targetPort: 8444
  - name: cert-https
    port: 8446
    targetPort: 8446
  type: LoadBalancer